### ISSUE TITLE
guilded.sh is incorrect

### ISSUE THREAD

**Issue by Hansyo** [KorbsStudio/Guilded-for-Linux#2]
Will the system environment be damaged if I install it with `guilded.sh`.
Specifically, it is
16 `sudo chmod -R 777 /usr/share/` and
17 `sudo chmod 777 /usr/share/Guilded.desktop` .
16 is purely unnecessary processing.
17 has specified the wrong path. Is it
`sudo chmod 755 /usr/share/applications/Guilded.desktop` correctly?
I would like you to correct it as soon as possible.

I'm not good at English, so I made this sentence by automatically translating my native language. I'm sorry if the expression is not good.

**Comment by MARK-PENGUIN** [comment]
I highly doubt the system would be damaged by installing this.
Also, yes, it is the wrong path. I'd certainly make a  pull request to fix this, but I guess the files aren't in source.

For now, here's an updated [guilded.sh](https://github.com/KorbsStudio/Guilded-for-Linux/files/4671478/guilded.sh.zip) which fixes this issue and enables verbose output (I didn't fix the line 16 issue because I'm a complete shellscript noob).

**Comment by KorbsStudio** [comment]
This was only tested on Elementary OS, therefore I can confirm it works fine on Ubuntu based distros.

**Comment by KorbsStudio** [comment]
The chmod command is used or else it won’t work for Zorin users, something I ran into with my Twitterr app.
